language: python

python:
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libenchant-dev

install:
  - pip install -r requirements.txt

script:
  - coverage run -m pytest
  - codecov
